# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/view/view_heros/book_warrior_page.ui'
#
# Created: Sat Jan 31 23:25:08 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWarriorPage(object):
    def setupUi(self, BookWarriorPage):
        BookWarriorPage.setObjectName("BookWarriorPage")
        BookWarriorPage.resize(929, 620)
        BookWarriorPage.setStyleSheet("")
        self.formLayout_2 = QtWidgets.QFormLayout(BookWarriorPage)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.widget = QtWidgets.QWidget(BookWarriorPage)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.picture_widget = QtWidgets.QWidget(self.widget)
        self.picture_widget.setMinimumSize(QtCore.QSize(333, 500))
        self.picture_widget.setObjectName("picture_widget")
        self.picture_layout_2 = QtWidgets.QVBoxLayout(self.picture_widget)
        self.picture_layout_2.setContentsMargins(0, 0, 0, 0)
        self.picture_layout_2.setObjectName("picture_layout_2")
        self.horizontalLayout_2.addWidget(self.picture_widget)
        self.actions_widget = QtWidgets.QWidget(self.widget)
        self.actions_widget.setObjectName("actions_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.actions_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.actions_widget)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/24x24/home"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.actions_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.actions_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addWidget(self.actions_widget)
        self.infos_widget = QtWidgets.QWidget(self.widget)
        self.infos_widget.setObjectName("infos_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infos_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupe_texture_button = QtWidgets.QPushButton(self.infos_widget)
        self.groupe_texture_button.setText("")
        self.groupe_texture_button.setObjectName("groupe_texture_button")
        self.verticalLayout_3.addWidget(self.groupe_texture_button)
        self.belong_widget = QtWidgets.QWidget(self.infos_widget)
        self.belong_widget.setObjectName("belong_widget")
        self.belong_layout = QtWidgets.QHBoxLayout(self.belong_widget)
        self.belong_layout.setContentsMargins(0, 0, 0, 0)
        self.belong_layout.setObjectName("belong_layout")
        self.flag = QtWidgets.QPushButton(self.belong_widget)
        self.flag.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/flags/blue_flag"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flag.setIcon(icon1)
        self.flag.setIconSize(QtCore.QSize(32, 32))
        self.flag.setFlat(True)
        self.flag.setObjectName("flag")
        self.belong_layout.addWidget(self.flag)
        self.pushButton_5 = QtWidgets.QPushButton(self.belong_widget)
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/empireIcon/greek_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.belong_layout.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.belong_widget)
        self.rank_widget = QtWidgets.QWidget(self.infos_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rank_widget.sizePolicy().hasHeightForWidth())
        self.rank_widget.setSizePolicy(sizePolicy)
        self.rank_widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rank_widget.setObjectName("rank_widget")
        self.layout_rank = QtWidgets.QHBoxLayout(self.rank_widget)
        self.layout_rank.setContentsMargins(0, 0, 0, 0)
        self.layout_rank.setObjectName("layout_rank")
        self.verticalLayout_3.addWidget(self.rank_widget)
        self.jauges_widget = QtWidgets.QWidget(self.infos_widget)
        self.jauges_widget.setObjectName("jauges_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.jauges_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.progressBar_HP = QtWidgets.QProgressBar(self.jauges_widget)
        self.progressBar_HP.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.progressBar_HP.setProperty("value", 24)
        self.progressBar_HP.setTextVisible(True)
        self.progressBar_HP.setInvertedAppearance(False)
        self.progressBar_HP.setObjectName("progressBar_HP")
        self.verticalLayout_4.addWidget(self.progressBar_HP)
        self.progressBar_MP = QtWidgets.QProgressBar(self.jauges_widget)
        self.progressBar_MP.setProperty("value", 24)
        self.progressBar_MP.setObjectName("progressBar_MP")
        self.verticalLayout_4.addWidget(self.progressBar_MP)
        self.verticalLayout_3.addWidget(self.jauges_widget)
        self.groupBox = QtWidgets.QGroupBox(self.infos_widget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_faction = QtWidgets.QLabel(self.groupBox)
        self.label_faction.setObjectName("label_faction")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_faction)
        self.label_empire = QtWidgets.QLabel(self.groupBox)
        self.label_empire.setObjectName("label_empire")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_empire)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_royaume = QtWidgets.QLabel(self.groupBox)
        self.label_royaume.setObjectName("label_royaume")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_royaume)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.informations_widget = QtWidgets.QWidget(self.infos_widget)
        self.informations_widget.setObjectName("informations_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.informations_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.informations_widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_4.setObjectName("widget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setAccelerated(True)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setAccelerated(True)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setAccelerated(True)
        self.spinBox_5.setObjectName("spinBox_5")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_5)
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setAccelerated(True)
        self.spinBox_6.setObjectName("spinBox_6")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_6)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_3.setObjectName("widget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.spinBox = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setAccelerated(True)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setAccelerated(True)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setAccelerated(True)
        self.spinBox_7.setProperty("showGroupSeparator", False)
        self.spinBox_7.setObjectName("spinBox_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_7)
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_8.setFrame(False)
        self.spinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setAccelerated(True)
        self.spinBox_8.setObjectName("spinBox_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_8)
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.informations_widget)
        self.horizontalLayout_2.addWidget(self.infos_widget)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget)
        self.right_page = QtWidgets.QWidget(BookWarriorPage)
        self.right_page.setObjectName("right_page")
        self.right_page_layout = QtWidgets.QVBoxLayout(self.right_page)
        self.right_page_layout.setContentsMargins(0, 0, 0, 0)
        self.right_page_layout.setObjectName("right_page_layout")
        self.warrior_name = QtWidgets.QLabel(self.right_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warrior_name.sizePolicy().hasHeightForWidth())
        self.warrior_name.setSizePolicy(sizePolicy)
        self.warrior_name.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(24)
        self.warrior_name.setFont(font)
        self.warrior_name.setFrameShape(QtWidgets.QFrame.Panel)
        self.warrior_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warrior_name.setAlignment(QtCore.Qt.AlignCenter)
        self.warrior_name.setObjectName("warrior_name")
        self.right_page_layout.addWidget(self.warrior_name)
        self.label_5 = QtWidgets.QLabel(self.right_page)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.right_page_layout.addWidget(self.label_5)
        self.listWidget = QtWidgets.QListWidget(self.right_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget.setObjectName("listWidget")
        self.right_page_layout.addWidget(self.listWidget)
        self.label_6 = QtWidgets.QLabel(self.right_page)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.right_page_layout.addWidget(self.label_6)
        self.scrollArea = QtWidgets.QScrollArea(self.right_page)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 100))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.vignettes = QtWidgets.QWidget()
        self.vignettes.setGeometry(QtCore.QRect(0, 0, 231, 98))
        self.vignettes.setObjectName("vignettes")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.vignettes)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea.setWidget(self.vignettes)
        self.right_page_layout.addWidget(self.scrollArea)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.right_page)

        self.retranslateUi(BookWarriorPage)
        QtCore.QMetaObject.connectSlotsByName(BookWarriorPage)

    def retranslateUi(self, BookWarriorPage):
        _translate = QtCore.QCoreApplication.translate
        BookWarriorPage.setWindowTitle(_translate("BookWarriorPage", "Form"))
        self.groupBox.setTitle(_translate("BookWarriorPage", "Informations"))
        self.label.setText(_translate("BookWarriorPage", "Faction"))
        self.label_2.setText(_translate("BookWarriorPage", "Empire"))
        self.label_faction.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_empire.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_17.setText(_translate("BookWarriorPage", "Kingdom"))
        self.label_royaume.setText(_translate("BookWarriorPage", "TextLabel"))
        self.groupBox_2.setTitle(_translate("BookWarriorPage", "Attributes"))
        self.label_10.setText(_translate("BookWarriorPage", "ATK"))
        self.label_11.setText(_translate("BookWarriorPage", "HP"))
        self.label_13.setText(_translate("BookWarriorPage", "MATK"))
        self.label_14.setText(_translate("BookWarriorPage", "AGL"))
        self.label_9.setText(_translate("BookWarriorPage", "DEF"))
        self.label_12.setText(_translate("BookWarriorPage", "MP"))
        self.label_15.setText(_translate("BookWarriorPage", "MDEF"))
        self.label_16.setText(_translate("BookWarriorPage", "LUCK"))
        self.warrior_name.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_5.setText(_translate("BookWarriorPage", "Historique"))
        self.label_6.setText(_translate("BookWarriorPage", "Gallerie"))

import resources_rc
