# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/view/view_heros/warrior_layout.ui'
#
# Created: Wed Jan 14 21:14:51 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WarriorLayout(object):
    def setupUi(self, WarriorLayout):
        WarriorLayout.setObjectName("WarriorLayout")
        WarriorLayout.resize(527, 427)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WarriorLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(WarriorLayout)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.preset_widget = QtWidgets.QWidget(self.widget)
        self.preset_widget.setObjectName("preset_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.preset_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preset_all_button = QtWidgets.QPushButton(self.preset_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_all_button.sizePolicy().hasHeightForWidth())
        self.preset_all_button.setSizePolicy(sizePolicy)
        self.preset_all_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/32x32/all"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preset_all_button.setIcon(icon)
        self.preset_all_button.setIconSize(QtCore.QSize(32, 32))
        self.preset_all_button.setCheckable(True)
        self.preset_all_button.setAutoExclusive(True)
        self.preset_all_button.setFlat(True)
        self.preset_all_button.setObjectName("preset_all_button")
        self.verticalLayout_2.addWidget(self.preset_all_button)
        self.preset_filtre_button = QtWidgets.QPushButton(self.preset_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_filtre_button.sizePolicy().hasHeightForWidth())
        self.preset_filtre_button.setSizePolicy(sizePolicy)
        self.preset_filtre_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/32x32/filtered"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preset_filtre_button.setIcon(icon1)
        self.preset_filtre_button.setIconSize(QtCore.QSize(32, 32))
        self.preset_filtre_button.setCheckable(True)
        self.preset_filtre_button.setAutoExclusive(True)
        self.preset_filtre_button.setDefault(False)
        self.preset_filtre_button.setFlat(True)
        self.preset_filtre_button.setObjectName("preset_filtre_button")
        self.verticalLayout_2.addWidget(self.preset_filtre_button)
        self.preset_selection_button = QtWidgets.QPushButton(self.preset_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_selection_button.sizePolicy().hasHeightForWidth())
        self.preset_selection_button.setSizePolicy(sizePolicy)
        self.preset_selection_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/32x32/selected"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preset_selection_button.setIcon(icon2)
        self.preset_selection_button.setIconSize(QtCore.QSize(32, 32))
        self.preset_selection_button.setCheckable(True)
        self.preset_selection_button.setAutoExclusive(True)
        self.preset_selection_button.setFlat(True)
        self.preset_selection_button.setObjectName("preset_selection_button")
        self.verticalLayout_2.addWidget(self.preset_selection_button)
        self.verticalLayout.addWidget(self.preset_widget)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.previous_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_button.sizePolicy().hasHeightForWidth())
        self.previous_button.setSizePolicy(sizePolicy)
        self.previous_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/24x24/previous"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_button.setIcon(icon3)
        self.previous_button.setIconSize(QtCore.QSize(24, 24))
        self.previous_button.setObjectName("previous_button")
        self.verticalLayout.addWidget(self.previous_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 10)
        self.horizontalLayout.addWidget(self.widget)
        self.next_button = QtWidgets.QPushButton(WarriorLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/24x24/next"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon4)
        self.next_button.setIconSize(QtCore.QSize(24, 24))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(WarriorLayout)
        QtCore.QMetaObject.connectSlotsByName(WarriorLayout)

    def retranslateUi(self, WarriorLayout):
        _translate = QtCore.QCoreApplication.translate
        WarriorLayout.setWindowTitle(_translate("WarriorLayout", "Form"))
        self.pushButton_2.setText(_translate("WarriorLayout", "Random"))
        self.previous_button.setShortcut(_translate("WarriorLayout", "Left"))
        self.next_button.setShortcut(_translate("WarriorLayout", "Right"))

import resources_rc
