# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/main_view/dialog_save.ui'
#
# Created: Sat Dec 20 22:14:13 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSave(object):
    def setupUi(self, DialogSave):
        DialogSave.setObjectName("DialogSave")
        DialogSave.setWindowModality(QtCore.Qt.NonModal)
        DialogSave.resize(489, 369)
        DialogSave.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DialogSave)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(DialogSave)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_nb_modified_kingdom_2 = QtWidgets.QLabel(self.widget_5)
        self.label_nb_modified_kingdom_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nb_modified_kingdom_2.setObjectName("label_nb_modified_kingdom_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_nb_modified_kingdom_2)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.list_modified_heros = QtWidgets.QListWidget(self.widget)
        self.list_modified_heros.setObjectName("list_modified_heros")
        self.verticalLayout_2.addWidget(self.list_modified_heros)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget_6)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_nb_modified_kingdom = QtWidgets.QLabel(self.widget_6)
        self.label_nb_modified_kingdom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nb_modified_kingdom.setObjectName("label_nb_modified_kingdom")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_nb_modified_kingdom)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.list_modified_kingdom = QtWidgets.QListWidget(self.widget)
        self.list_modified_kingdom.setObjectName("list_modified_kingdom")
        self.verticalLayout_2.addWidget(self.list_modified_kingdom)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_nb_modified_groupes = QtWidgets.QLabel(self.widget_7)
        self.label_nb_modified_groupes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nb_modified_groupes.setObjectName("label_nb_modified_groupes")
        self.horizontalLayout_2.addWidget(self.label_nb_modified_groupes)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.list_modified_groupes = QtWidgets.QListWidget(self.widget)
        self.list_modified_groupes.setObjectName("list_modified_groupes")
        self.verticalLayout_2.addWidget(self.list_modified_groupes)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(DialogSave)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.formLayout = QtWidgets.QFormLayout(self.widget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.tous_checkbox = QtWidgets.QCheckBox(self.widget_3)
        self.tous_checkbox.setChecked(True)
        self.tous_checkbox.setAutoExclusive(True)
        self.tous_checkbox.setObjectName("tous_checkbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tous_checkbox)
        self.aucun_checkbox = QtWidgets.QCheckBox(self.widget_3)
        self.aucun_checkbox.setAutoExclusive(True)
        self.aucun_checkbox.setObjectName("aucun_checkbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aucun_checkbox)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setText("")
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addWidget(self.widget_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(DialogSave)
        QtCore.QMetaObject.connectSlotsByName(DialogSave)

    def retranslateUi(self, DialogSave):
        _translate = QtCore.QCoreApplication.translate
        DialogSave.setWindowTitle(_translate("DialogSave", "Dialog"))
        self.label_8.setText(_translate("DialogSave", "Heros :"))
        self.label_nb_modified_kingdom_2.setText(_translate("DialogSave", "TextLabel"))
        self.label_7.setText(_translate("DialogSave", "Royaumes :"))
        self.label_nb_modified_kingdom.setText(_translate("DialogSave", "TextLabel"))
        self.label_2.setText(_translate("DialogSave", "Groupes :"))
        self.label_nb_modified_groupes.setText(_translate("DialogSave", "TextLabel"))
        self.tous_checkbox.setText(_translate("DialogSave", "Tous"))
        self.aucun_checkbox.setText(_translate("DialogSave", "Aucun"))

