# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/main_view/dialog_import_groupe.ui'
#
# Created: Wed Oct 21 21:03:24 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogGroupeImport(object):
    def setupUi(self, DialogGroupeImport):
        DialogGroupeImport.setObjectName("DialogGroupeImport")
        DialogGroupeImport.resize(504, 398)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DialogGroupeImport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(DialogGroupeImport)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditGroupe = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditGroupe.setObjectName("lineEditGroupe")
        self.horizontalLayout_2.addWidget(self.lineEditGroupe)
        self.toolButtonGroupe = QtWidgets.QToolButton(self.widget_2)
        self.toolButtonGroupe.setObjectName("toolButtonGroupe")
        self.horizontalLayout_2.addWidget(self.toolButtonGroupe)
        self.verticalLayout.addWidget(self.widget_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.groupe_description = QtWidgets.QLineEdit(self.groupBox_3)
        self.groupe_description.setObjectName("groupe_description")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupe_description)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.groupe_rank = QtWidgets.QSpinBox(self.groupBox_3)
        self.groupe_rank.setObjectName("groupe_rank")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupe_rank)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.groupe_color = QtWidgets.QComboBox(self.groupBox_3)
        self.groupe_color.setObjectName("groupe_color")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.groupe_color)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.heros_latitude = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.heros_latitude.setObjectName("heros_latitude")
        self.horizontalLayout_3.addWidget(self.heros_latitude)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.heros_longitude = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.heros_longitude.setObjectName("heros_longitude")
        self.horizontalLayout_3.addWidget(self.heros_longitude)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.heros_place = QtWidgets.QSpinBox(self.widget_3)
        self.heros_place.setMinimum(-1)
        self.heros_place.setObjectName("heros_place")
        self.horizontalLayout_3.addWidget(self.heros_place)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.heros_level = QtWidgets.QSpinBox(self.widget_3)
        self.heros_level.setMinimum(-1)
        self.heros_level.setObjectName("heros_level")
        self.horizontalLayout_3.addWidget(self.heros_level)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setObjectName("widget_4")
        self.formLayout = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.heros_description = QtWidgets.QLineEdit(self.widget_4)
        self.heros_description.setObjectName("heros_description")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.heros_description)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.heros_techniques = QtWidgets.QLineEdit(self.widget_4)
        self.heros_techniques.setObjectName("heros_techniques")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.heros_techniques)
        self.heros_historique = QtWidgets.QLineEdit(self.widget_4)
        self.heros_historique.setObjectName("heros_historique")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heros_historique)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.heros_leader = QtWidgets.QCheckBox(self.widget_5)
        self.heros_leader.setText("")
        self.heros_leader.setObjectName("heros_leader")
        self.horizontalLayout_5.addWidget(self.heros_leader)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.heros_rank = QtWidgets.QSpinBox(self.widget_5)
        self.heros_rank.setObjectName("heros_rank")
        self.horizontalLayout_5.addWidget(self.heros_rank)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.heros_status = QtWidgets.QComboBox(self.widget_5)
        self.heros_status.setObjectName("heros_status")
        self.horizontalLayout_5.addWidget(self.heros_status)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogGroupeImport)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogGroupeImport)
        self.buttonBox.accepted.connect(DialogGroupeImport.accept)
        self.buttonBox.rejected.connect(DialogGroupeImport.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogGroupeImport)

    def retranslateUi(self, DialogGroupeImport):
        _translate = QtCore.QCoreApplication.translate
        DialogGroupeImport.setWindowTitle(_translate("DialogGroupeImport", "Dialog"))
        self.label.setText(_translate("DialogGroupeImport", "Groupe  Dir"))
        self.toolButtonGroupe.setText(_translate("DialogGroupeImport", "..."))
        self.groupBox_3.setTitle(_translate("DialogGroupeImport", "Paramètres par defaut Groupes"))
        self.label_18.setText(_translate("DialogGroupeImport", "Description"))
        self.label_19.setText(_translate("DialogGroupeImport", "Rank"))
        self.label_20.setText(_translate("DialogGroupeImport", "Color"))
        self.groupBox.setTitle(_translate("DialogGroupeImport", "Parametres par default Heros : "))
        self.label_2.setText(_translate("DialogGroupeImport", "Lat :"))
        self.label_3.setText(_translate("DialogGroupeImport", "Lon :"))
        self.label_5.setText(_translate("DialogGroupeImport", "Place"))
        self.label_6.setText(_translate("DialogGroupeImport", "Level"))
        self.label_4.setText(_translate("DialogGroupeImport", "Description"))
        self.label_8.setText(_translate("DialogGroupeImport", "Techniques"))
        self.label_9.setText(_translate("DialogGroupeImport", "Historique"))
        self.label_7.setText(_translate("DialogGroupeImport", "Leader"))
        self.label_10.setText(_translate("DialogGroupeImport", "Rank"))
        self.label_11.setText(_translate("DialogGroupeImport", "Status"))

