# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/main_view/main_window.ui'
#
# Created: Fri Sep 25 23:10:56 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 883)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.map = QtWidgets.QWidget()
        self.map.setObjectName("map")
        self.map_layout = QtWidgets.QVBoxLayout(self.map)
        self.map_layout.setObjectName("map_layout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/32x32/map"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.map, icon, "")
        self.kingdoms = QtWidgets.QWidget()
        self.kingdoms.setObjectName("kingdoms")
        self.k_layout = QtWidgets.QHBoxLayout(self.kingdoms)
        self.k_layout.setObjectName("k_layout")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/32x32/fiche_royaume"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.kingdoms, icon1, "")
        self.warriors = QtWidgets.QWidget()
        self.warriors.setObjectName("warriors")
        self.w_layout = QtWidgets.QHBoxLayout(self.warriors)
        self.w_layout.setObjectName("w_layout")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/32x32/fiche_perso"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.warriors, icon2, "")
        self.book = QtWidgets.QWidget()
        self.book.setObjectName("book")
        self.b_layout = QtWidgets.QHBoxLayout(self.book)
        self.b_layout.setObjectName("b_layout")
        self.tabWidget.addTab(self.book, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuDesign = QtWidgets.QMenu(self.menubar)
        self.menuDesign.setObjectName("menuDesign")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.explorerDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.explorerDockWidget.setMinimumSize(QtCore.QSize(150, 800))
        self.explorerDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.explorerDockWidget.setObjectName("explorerDockWidget")
        self.explorer_content = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.explorer_content.sizePolicy().hasHeightForWidth())
        self.explorer_content.setSizePolicy(sizePolicy)
        self.explorer_content.setObjectName("explorer_content")
        self.explorerDockWidget.setWidget(self.explorer_content)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.explorerDockWidget)
        self.profilDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.profilDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.profilDockWidget.setObjectName("profilDockWidget")
        self.profil_content = QtWidgets.QWidget()
        self.profil_content.setObjectName("profil_content")
        self.profilDockWidget.setWidget(self.profil_content)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.profilDockWidget)
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/24x24/home"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon3)
        self.actionHome.setObjectName("actionHome")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/24x24/quit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/24x24/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionGenerate_Thumbnail = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Thumbnail.setObjectName("actionGenerate_Thumbnail")
        self.actionLaunch_SQlite = QtWidgets.QAction(MainWindow)
        self.actionLaunch_SQlite.setObjectName("actionLaunch_SQlite")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/24x24/settings"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon6)
        self.actionSettings.setObjectName("actionSettings")
        self.actionReset_attributes = QtWidgets.QAction(MainWindow)
        self.actionReset_attributes.setObjectName("actionReset_attributes")
        self.actionAdd_Kingdom = QtWidgets.QAction(MainWindow)
        self.actionAdd_Kingdom.setObjectName("actionAdd_Kingdom")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionStylesheet = QtWidgets.QAction(MainWindow)
        self.actionStylesheet.setObjectName("actionStylesheet")
        self.actionApplyStyleSheet = QtWidgets.QAction(MainWindow)
        self.actionApplyStyleSheet.setObjectName("actionApplyStyleSheet")
        self.actionSelection = QtWidgets.QAction(MainWindow)
        self.actionSelection.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/32x32/selected"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelection.setIcon(icon7)
        self.actionSelection.setObjectName("actionSelection")
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/32x32/filtered"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilter.setIcon(icon8)
        self.actionFilter.setObjectName("actionFilter")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/32x32/all"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAll.setIcon(icon9)
        self.actionAll.setObjectName("actionAll")
        self.menuFIle.addAction(self.actionNew)
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionSave_As)
        self.menuTools.addAction(self.actionGenerate_Thumbnail)
        self.menuTools.addAction(self.actionLaunch_SQlite)
        self.menuTools.addAction(self.actionReset_attributes)
        self.menuTools.addAction(self.actionAdd_Kingdom)
        self.menuDesign.addAction(self.actionStylesheet)
        self.menuDesign.addAction(self.actionApplyStyleSheet)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuDesign.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.book), _translate("MainWindow", "Page"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuTools.setTitle(_translate("MainWindow", "Database"))
        self.menuDesign.setTitle(_translate("MainWindow", "Tools"))
        self.explorerDockWidget.setWindowTitle(_translate("MainWindow", "Explorer"))
        self.profilDockWidget.setWindowTitle(_translate("MainWindow", "Profil"))
        self.actionHome.setText(_translate("MainWindow", "home"))
        self.actionQuit.setText(_translate("MainWindow", "quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save current modifications"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionGenerate_Thumbnail.setText(_translate("MainWindow", "Generate Thumbnail"))
        self.actionLaunch_SQlite.setText(_translate("MainWindow", "Launch SQlite"))
        self.actionSettings.setText(_translate("MainWindow", "settings"))
        self.actionReset_attributes.setText(_translate("MainWindow", "Reset attributes"))
        self.actionAdd_Kingdom.setText(_translate("MainWindow", "Add Kingdom"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionStylesheet.setText(_translate("MainWindow", "EditStyleSheet"))
        self.actionApplyStyleSheet.setText(_translate("MainWindow", "ApplyStyleSheet"))
        self.actionSelection.setText(_translate("MainWindow", "selection"))
        self.actionFilter.setText(_translate("MainWindow", "filter"))
        self.actionAll.setText(_translate("MainWindow", "all"))

import resources_rc
