# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/main_view/profil.ui'
#
# Created: Wed Oct 21 21:03:19 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProfilWidget(object):
    def setupUi(self, ProfilWidget):
        ProfilWidget.setObjectName("ProfilWidget")
        ProfilWidget.setWindowModality(QtCore.Qt.WindowModal)
        ProfilWidget.resize(150, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProfilWidget.sizePolicy().hasHeightForWidth())
        ProfilWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProfilWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.warrior_name = QtWidgets.QLabel(ProfilWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.warrior_name.setFont(font)
        self.warrior_name.setAlignment(QtCore.Qt.AlignCenter)
        self.warrior_name.setObjectName("warrior_name")
        self.verticalLayout.addWidget(self.warrior_name)
        self.picture = QtWidgets.QLabel(ProfilWidget)
        self.picture.setObjectName("picture")
        self.verticalLayout.addWidget(self.picture)
        self.rank_widget = QtWidgets.QWidget(ProfilWidget)
        self.rank_widget.setObjectName("rank_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.rank_widget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profil_completion = QtWidgets.QLabel(self.rank_widget)
        self.profil_completion.setObjectName("profil_completion")
        self.horizontalLayout_3.addWidget(self.profil_completion)
        self.rank_label = QtWidgets.QLabel(self.rank_widget)
        self.rank_label.setObjectName("rank_label")
        self.horizontalLayout_3.addWidget(self.rank_label)
        self.rank_text = QtWidgets.QLabel(self.rank_widget)
        self.rank_text.setObjectName("rank_text")
        self.horizontalLayout_3.addWidget(self.rank_text)
        self.iconState = QtWidgets.QLabel(self.rank_widget)
        self.iconState.setObjectName("iconState")
        self.horizontalLayout_3.addWidget(self.iconState)
        self.verticalLayout.addWidget(self.rank_widget)
        self.iconGroupe = QtWidgets.QPushButton(ProfilWidget)
        self.iconGroupe.setText("")
        self.iconGroupe.setObjectName("iconGroupe")
        self.verticalLayout.addWidget(self.iconGroupe)
        self.widget = QtWidgets.QWidget(ProfilWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconFaction = QtWidgets.QPushButton(self.widget)
        self.iconFaction.setText("")
        self.iconFaction.setIconSize(QtCore.QSize(16, 16))
        self.iconFaction.setObjectName("iconFaction")
        self.horizontalLayout.addWidget(self.iconFaction)
        self.iconEmpire = QtWidgets.QPushButton(self.widget)
        self.iconEmpire.setText("")
        self.iconEmpire.setIconSize(QtCore.QSize(16, 16))
        self.iconEmpire.setObjectName("iconEmpire")
        self.horizontalLayout.addWidget(self.iconEmpire)
        self.iconKingdom = QtWidgets.QPushButton(self.widget)
        self.iconKingdom.setText("")
        self.iconKingdom.setIconSize(QtCore.QSize(16, 16))
        self.iconKingdom.setObjectName("iconKingdom")
        self.horizontalLayout.addWidget(self.iconKingdom)
        self.verticalLayout.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(ProfilWidget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar_life = QtWidgets.QProgressBar(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_life.sizePolicy().hasHeightForWidth())
        self.progressBar_life.setSizePolicy(sizePolicy)
        self.progressBar_life.setProperty("value", 24)
        self.progressBar_life.setObjectName("progressBar_life")
        self.verticalLayout_2.addWidget(self.progressBar_life)
        self.progressBar_energy = QtWidgets.QProgressBar(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_energy.sizePolicy().hasHeightForWidth())
        self.progressBar_energy.setSizePolicy(sizePolicy)
        self.progressBar_energy.setProperty("value", 24)
        self.progressBar_energy.setObjectName("progressBar_energy")
        self.verticalLayout_2.addWidget(self.progressBar_energy)
        self.verticalLayout.addWidget(self.widget_5)
        self.list_selected = QtWidgets.QListWidget(ProfilWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_selected.sizePolicy().hasHeightForWidth())
        self.list_selected.setSizePolicy(sizePolicy)
        self.list_selected.setDragEnabled(True)
        self.list_selected.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.list_selected.setObjectName("list_selected")
        self.verticalLayout.addWidget(self.list_selected)
        self.list_selected2 = QtWidgets.QListWidget(ProfilWidget)
        self.list_selected2.setObjectName("list_selected2")
        self.verticalLayout.addWidget(self.list_selected2)

        self.retranslateUi(ProfilWidget)
        QtCore.QMetaObject.connectSlotsByName(ProfilWidget)

    def retranslateUi(self, ProfilWidget):
        _translate = QtCore.QCoreApplication.translate
        ProfilWidget.setWindowTitle(_translate("ProfilWidget", "Profil"))
        self.warrior_name.setText(_translate("ProfilWidget", "TextLabel"))
        self.picture.setText(_translate("ProfilWidget", "TextLabel"))
        self.profil_completion.setText(_translate("ProfilWidget", "TextLabel"))
        self.rank_label.setText(_translate("ProfilWidget", "Rank : "))
        self.rank_text.setText(_translate("ProfilWidget", "TextLabel"))
        self.iconState.setText(_translate("ProfilWidget", "TextLabel"))

