# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/view/view_kingdom/book_world_main_page.ui'
#
# Created: Wed Oct 21 21:03:13 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWorldMainpage(object):
    def setupUi(self, BookWorldMainpage):
        BookWorldMainpage.setObjectName("BookWorldMainpage")
        BookWorldMainpage.resize(566, 431)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookWorldMainpage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(BookWorldMainpage)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(24)
        self.Title.setFont(font)
        self.Title.setStyleSheet("")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_content2 = QtWidgets.QWidget(self.widget_4)
        self.widget_content2.setObjectName("widget_content2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_content2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_content2)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.progressBar = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.button_color = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_color.sizePolicy().hasHeightForWidth())
        self.button_color.setSizePolicy(sizePolicy)
        self.button_color.setAutoFillBackground(True)
        self.button_color.setText("")
        self.button_color.setObjectName("button_color")
        self.horizontalLayout_4.addWidget(self.button_color)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_7 = QtWidgets.QWidget(self.widget_content2)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.descriptionTextEdit = QtWidgets.QPlainTextEdit(self.widget_content2)
        self.descriptionTextEdit.setEnabled(True)
        self.descriptionTextEdit.setBackgroundVisible(False)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout_3.addWidget(self.descriptionTextEdit)
        self.horizontalLayout_2.addWidget(self.widget_content2)
        self.horizontalLayout_2.setStretch(0, 4)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_content = QtWidgets.QWidget(self.widget_3)
        self.widget_content.setObjectName("widget_content")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_content)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_content)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.historyTextEdit = QtWidgets.QPlainTextEdit(self.widget_content)
        self.historyTextEdit.setEnabled(True)
        self.historyTextEdit.setBackgroundVisible(False)
        self.historyTextEdit.setObjectName("historyTextEdit")
        self.verticalLayout_4.addWidget(self.historyTextEdit)
        self.horizontalLayout_3.addWidget(self.widget_content)
        self.horizontalLayout_3.setStretch(0, 4)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(2, 10)
        self.horizontalLayout.addWidget(self.widget)
        self.right_page = QtWidgets.QWidget(BookWorldMainpage)
        self.right_page.setObjectName("right_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_page)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.right_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.histo_warrior_page = QtWidgets.QWidget()
        self.histo_warrior_page.setObjectName("histo_warrior_page")
        self.histo_warrior_layout = QtWidgets.QVBoxLayout(self.histo_warrior_page)
        self.histo_warrior_layout.setContentsMargins(0, 0, 0, 0)
        self.histo_warrior_layout.setObjectName("histo_warrior_layout")
        self.tabWidget.addTab(self.histo_warrior_page, "")
        self.pie_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pie_page.sizePolicy().hasHeightForWidth())
        self.pie_page.setSizePolicy(sizePolicy)
        self.pie_page.setObjectName("pie_page")
        self.pie_layout = QtWidgets.QVBoxLayout(self.pie_page)
        self.pie_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.pie_layout.setObjectName("pie_layout")
        self.tabWidget.addTab(self.pie_page, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.groupe_boutton = QtWidgets.QWidget(self.right_page)
        self.groupe_boutton.setObjectName("groupe_boutton")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupe_boutton)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupe_boutton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.groupes_buttons = QtWidgets.QWidget()
        self.groupes_buttons.setGeometry(QtCore.QRect(0, 0, 184, 118))
        self.groupes_buttons.setObjectName("groupes_buttons")
        self.groupes_bouttons_layout = QtWidgets.QGridLayout(self.groupes_buttons)
        self.groupes_bouttons_layout.setContentsMargins(0, 0, 0, 0)
        self.groupes_bouttons_layout.setObjectName("groupes_bouttons_layout")
        self.scrollArea_3.setWidget(self.groupes_buttons)
        self.verticalLayout_11.addWidget(self.scrollArea_3)
        self.verticalLayout_2.addWidget(self.groupe_boutton)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.right_page)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(BookWorldMainpage)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BookWorldMainpage)

    def retranslateUi(self, BookWorldMainpage):
        _translate = QtCore.QCoreApplication.translate
        BookWorldMainpage.setWindowTitle(_translate("BookWorldMainpage", "Form"))
        self.Title.setText(_translate("BookWorldMainpage", "Artemis"))
        self.label_4.setText(_translate("BookWorldMainpage", "Completion :"))
        self.label_3.setText(_translate("BookWorldMainpage", "Warriors :"))
        self.label.setText(_translate("BookWorldMainpage", "Description"))
        self.label_2.setText(_translate("BookWorldMainpage", "Histoire"))

import resources_rc
