# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/view/view_kingdom/book_world_homepage.ui'
#
# Created: Sat Dec 20 22:14:10 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWorldHomepage(object):
    def setupUi(self, BookWorldHomepage):
        BookWorldHomepage.setObjectName("BookWorldHomepage")
        BookWorldHomepage.resize(487, 350)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookWorldHomepage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(BookWorldHomepage)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.faction_left = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faction_left.sizePolicy().hasHeightForWidth())
        self.faction_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        self.faction_left.setFont(font)
        self.faction_left.setAlignment(QtCore.Qt.AlignCenter)
        self.faction_left.setObjectName("faction_left")
        self.horizontalLayout_2.addWidget(self.faction_left)
        self.faction_right = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faction_right.sizePolicy().hasHeightForWidth())
        self.faction_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        self.faction_right.setFont(font)
        self.faction_right.setAlignment(QtCore.Qt.AlignCenter)
        self.faction_right.setObjectName("faction_right")
        self.horizontalLayout_2.addWidget(self.faction_right)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.empire_left = QtWidgets.QWidget(self.widget_4)
        self.empire_left.setObjectName("empire_left")
        self.empire_left_layout = QtWidgets.QVBoxLayout(self.empire_left)
        self.empire_left_layout.setSpacing(20)
        self.empire_left_layout.setContentsMargins(0, 0, 0, 0)
        self.empire_left_layout.setObjectName("empire_left_layout")
        self.horizontalLayout_3.addWidget(self.empire_left)
        self.empire_right = QtWidgets.QWidget(self.widget_4)
        self.empire_right.setObjectName("empire_right")
        self.empire_right_layout = QtWidgets.QVBoxLayout(self.empire_right)
        self.empire_right_layout.setSpacing(20)
        self.empire_right_layout.setContentsMargins(0, 0, 0, 0)
        self.empire_right_layout.setObjectName("empire_right_layout")
        self.horizontalLayout_3.addWidget(self.empire_right)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(BookWorldHomepage)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.right_empire_name = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_empire_name.sizePolicy().hasHeightForWidth())
        self.right_empire_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.right_empire_name.setFont(font)
        self.right_empire_name.setText("")
        self.right_empire_name.setAlignment(QtCore.Qt.AlignCenter)
        self.right_empire_name.setObjectName("right_empire_name")
        self.verticalLayout.addWidget(self.right_empire_name)
        self.resume_textEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.resume_textEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resume_textEdit.sizePolicy().hasHeightForWidth())
        self.resume_textEdit.setSizePolicy(sizePolicy)
        self.resume_textEdit.setObjectName("resume_textEdit")
        self.verticalLayout.addWidget(self.resume_textEdit)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 121, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(BookWorldHomepage)
        QtCore.QMetaObject.connectSlotsByName(BookWorldHomepage)

    def retranslateUi(self, BookWorldHomepage):
        _translate = QtCore.QCoreApplication.translate
        BookWorldHomepage.setWindowTitle(_translate("BookWorldHomepage", "Form"))
        self.faction_left.setText(_translate("BookWorldHomepage", "TextLabel"))
        self.faction_right.setText(_translate("BookWorldHomepage", "TextLabel"))

