# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/view/view_kingdom/book_world_homepage.ui'
#
# Created: Thu Sep 10 22:05:22 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWorldHomepage(object):
    def setupUi(self, BookWorldHomepage):
        BookWorldHomepage.setObjectName("BookWorldHomepage")
        BookWorldHomepage.resize(487, 350)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookWorldHomepage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(BookWorldHomepage)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.faction_left = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faction_left.sizePolicy().hasHeightForWidth())
        self.faction_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        self.faction_left.setFont(font)
        self.faction_left.setAlignment(QtCore.Qt.AlignCenter)
        self.faction_left.setObjectName("faction_left")
        self.horizontalLayout_2.addWidget(self.faction_left)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/32x32/kingdom"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.faction_right = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faction_right.sizePolicy().hasHeightForWidth())
        self.faction_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        self.faction_right.setFont(font)
        self.faction_right.setAlignment(QtCore.Qt.AlignCenter)
        self.faction_right.setObjectName("faction_right")
        self.horizontalLayout_2.addWidget(self.faction_right)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.empire_left_pies = QtWidgets.QWidget(self.widget)
        self.empire_left_pies.setObjectName("empire_left_pies")
        self.pie_left_layout_2 = QtWidgets.QHBoxLayout(self.empire_left_pies)
        self.pie_left_layout_2.setSpacing(0)
        self.pie_left_layout_2.setContentsMargins(0, 0, 0, 0)
        self.pie_left_layout_2.setObjectName("pie_left_layout_2")
        self.faction_left_pie = QtWidgets.QWidget(self.empire_left_pies)
        self.faction_left_pie.setObjectName("faction_left_pie")
        self.faction_left_pie_layout = QtWidgets.QVBoxLayout(self.faction_left_pie)
        self.faction_left_pie_layout.setContentsMargins(0, 0, 0, 0)
        self.faction_left_pie_layout.setObjectName("faction_left_pie_layout")
        self.pie_left_layout_2.addWidget(self.faction_left_pie)
        self.faction_right_pie = QtWidgets.QWidget(self.empire_left_pies)
        self.faction_right_pie.setObjectName("faction_right_pie")
        self.faction_right_pie_layout = QtWidgets.QVBoxLayout(self.faction_right_pie)
        self.faction_right_pie_layout.setContentsMargins(0, 0, 0, 0)
        self.faction_right_pie_layout.setObjectName("faction_right_pie_layout")
        self.pie_left_layout_2.addWidget(self.faction_right_pie)
        self.verticalLayout_3.addWidget(self.empire_left_pies)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.empire_left = QtWidgets.QWidget(self.widget_4)
        self.empire_left.setObjectName("empire_left")
        self.empire_left_layout = QtWidgets.QVBoxLayout(self.empire_left)
        self.empire_left_layout.setSpacing(20)
        self.empire_left_layout.setContentsMargins(0, 0, 0, 0)
        self.empire_left_layout.setObjectName("empire_left_layout")
        self.horizontalLayout_3.addWidget(self.empire_left)
        self.empire_right = QtWidgets.QWidget(self.widget_4)
        self.empire_right.setObjectName("empire_right")
        self.empire_right_layout = QtWidgets.QVBoxLayout(self.empire_right)
        self.empire_right_layout.setSpacing(20)
        self.empire_right_layout.setContentsMargins(0, 0, 0, 0)
        self.empire_right_layout.setObjectName("empire_right_layout")
        self.horizontalLayout_3.addWidget(self.empire_right)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 4)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(BookWorldHomepage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.right_empire_name = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_empire_name.sizePolicy().hasHeightForWidth())
        self.right_empire_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.right_empire_name.setFont(font)
        self.right_empire_name.setText("")
        self.right_empire_name.setAlignment(QtCore.Qt.AlignCenter)
        self.right_empire_name.setObjectName("right_empire_name")
        self.verticalLayout.addWidget(self.right_empire_name)
        self.resume_textEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.resume_textEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resume_textEdit.sizePolicy().hasHeightForWidth())
        self.resume_textEdit.setSizePolicy(sizePolicy)
        self.resume_textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.resume_textEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.resume_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.resume_textEdit.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.resume_textEdit.setObjectName("resume_textEdit")
        self.verticalLayout.addWidget(self.resume_textEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.kingdom_contribution_page = QtWidgets.QWidget()
        self.kingdom_contribution_page.setObjectName("kingdom_contribution_page")
        self.kingdom_page_layout = QtWidgets.QVBoxLayout(self.kingdom_contribution_page)
        self.kingdom_page_layout.setContentsMargins(0, 0, 0, 0)
        self.kingdom_page_layout.setObjectName("kingdom_page_layout")
        self.stackedWidget.addWidget(self.kingdom_contribution_page)
        self.kingdom_histo = QtWidgets.QWidget()
        self.kingdom_histo.setObjectName("kingdom_histo")
        self.kingdom_histo_layout = QtWidgets.QVBoxLayout(self.kingdom_histo)
        self.kingdom_histo_layout.setObjectName("kingdom_histo_layout")
        self.stackedWidget.addWidget(self.kingdom_histo)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.net_chart_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_chart_button.sizePolicy().hasHeightForWidth())
        self.net_chart_button.setSizePolicy(sizePolicy)
        self.net_chart_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/24x24/next"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.net_chart_button.setIcon(icon1)
        self.net_chart_button.setObjectName("net_chart_button")
        self.horizontalLayout_4.addWidget(self.net_chart_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 71, 91))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(BookWorldHomepage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BookWorldHomepage)

    def retranslateUi(self, BookWorldHomepage):
        _translate = QtCore.QCoreApplication.translate
        BookWorldHomepage.setWindowTitle(_translate("BookWorldHomepage", "Form"))
        self.faction_left.setText(_translate("BookWorldHomepage", "TextLabel"))
        self.faction_right.setText(_translate("BookWorldHomepage", "TextLabel"))

import resources_rc
