# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/View/book_world_army.ui'
#
# Created: Tue Dec  9 22:08:13 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWorldArmy(object):
    def setupUi(self, BookWorldArmy):
        BookWorldArmy.setObjectName("BookWorldArmy")
        BookWorldArmy.resize(729, 343)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookWorldArmy)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_page = QtWidgets.QWidget(BookWorldArmy)
        self.left_page.setObjectName("left_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.left_page)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_gauche = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(24)
        self.title_gauche.setFont(font)
        self.title_gauche.setAlignment(QtCore.Qt.AlignCenter)
        self.title_gauche.setObjectName("title_gauche")
        self.horizontalLayout_2.addWidget(self.title_gauche)
        self.comboBoxColorLeft = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxColorLeft.sizePolicy().hasHeightForWidth())
        self.comboBoxColorLeft.setSizePolicy(sizePolicy)
        self.comboBoxColorLeft.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBoxColorLeft.setIconSize(QtCore.QSize(32, 16))
        self.comboBoxColorLeft.setObjectName("comboBoxColorLeft")
        self.horizontalLayout_2.addWidget(self.comboBoxColorLeft)
        self.verticalLayout.addWidget(self.widget)
        self.description_gauche = QtWidgets.QPlainTextEdit(self.left_page)
        self.description_gauche.setObjectName("description_gauche")
        self.verticalLayout.addWidget(self.description_gauche)
        self.scrollArea = QtWidgets.QScrollArea(self.left_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.vignettes_gauche = QtWidgets.QWidget()
        self.vignettes_gauche.setGeometry(QtCore.QRect(0, 0, 333, 167))
        self.vignettes_gauche.setObjectName("vignettes_gauche")
        self.gridLayout = QtWidgets.QGridLayout(self.vignettes_gauche)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.vignettes_gauche)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 20)
        self.horizontalLayout.addWidget(self.left_page)
        self.right_page = QtWidgets.QWidget(BookWorldArmy)
        self.right_page.setObjectName("right_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.right_page)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_droite = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(24)
        self.title_droite.setFont(font)
        self.title_droite.setAlignment(QtCore.Qt.AlignCenter)
        self.title_droite.setObjectName("title_droite")
        self.horizontalLayout_3.addWidget(self.title_droite)
        self.comboBoxColorRight = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxColorRight.sizePolicy().hasHeightForWidth())
        self.comboBoxColorRight.setSizePolicy(sizePolicy)
        self.comboBoxColorRight.setIconSize(QtCore.QSize(32, 16))
        self.comboBoxColorRight.setObjectName("comboBoxColorRight")
        self.horizontalLayout_3.addWidget(self.comboBoxColorRight)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.description_droite = QtWidgets.QPlainTextEdit(self.right_page)
        self.description_droite.setObjectName("description_droite")
        self.verticalLayout_2.addWidget(self.description_droite)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.right_page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.vignettes_droite = QtWidgets.QWidget()
        self.vignettes_droite.setGeometry(QtCore.QRect(0, 0, 332, 167))
        self.vignettes_droite.setObjectName("vignettes_droite")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.vignettes_droite)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2.setWidget(self.vignettes_droite)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 20)
        self.horizontalLayout.addWidget(self.right_page)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(BookWorldArmy)
        QtCore.QMetaObject.connectSlotsByName(BookWorldArmy)

    def retranslateUi(self, BookWorldArmy):
        _translate = QtCore.QCoreApplication.translate
        BookWorldArmy.setWindowTitle(_translate("BookWorldArmy", "Form"))
        self.title_gauche.setText(_translate("BookWorldArmy", "TextLabel"))
        self.title_droite.setText(_translate("BookWorldArmy", "TextLabel"))

import resources_rc
