# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/View/book_container.ui'
#
# Created: Tue Dec  9 22:08:11 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookViewContainer(object):
    def setupUi(self, BookViewContainer):
        BookViewContainer.setObjectName("BookViewContainer")
        BookViewContainer.resize(1273, 709)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BookViewContainer.sizePolicy().hasHeightForWidth())
        BookViewContainer.setSizePolicy(sizePolicy)
        BookViewContainer.setWindowTitle("")
        BookViewContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        BookViewContainer.setTabPosition(QtWidgets.QTabWidget.North)
        BookViewContainer.setTabShape(QtWidgets.QTabWidget.Rounded)
        BookViewContainer.setIconSize(QtCore.QSize(32, 32))
        BookViewContainer.setElideMode(QtCore.Qt.ElideMiddle)
        BookViewContainer.setDocumentMode(False)
        BookViewContainer.setTabsClosable(False)
        self.Kingdoms = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Kingdoms.sizePolicy().hasHeightForWidth())
        self.Kingdoms.setSizePolicy(sizePolicy)
        self.Kingdoms.setObjectName("Kingdoms")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Kingdoms)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kingdom_previous_button = QtWidgets.QPushButton(self.Kingdoms)
        self.kingdom_previous_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kingdom_previous_button.sizePolicy().hasHeightForWidth())
        self.kingdom_previous_button.setSizePolicy(sizePolicy)
        self.kingdom_previous_button.setMinimumSize(QtCore.QSize(0, 0))
        self.kingdom_previous_button.setObjectName("kingdom_previous_button")
        self.horizontalLayout.addWidget(self.kingdom_previous_button)
        self.stackedWidget_kingdoms = QtWidgets.QStackedWidget(self.Kingdoms)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_kingdoms.sizePolicy().hasHeightForWidth())
        self.stackedWidget_kingdoms.setSizePolicy(sizePolicy)
        self.stackedWidget_kingdoms.setMinimumSize(QtCore.QSize(200, 200))
        self.stackedWidget_kingdoms.setObjectName("stackedWidget_kingdoms")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_kingdoms.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_kingdoms.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget_kingdoms)
        self.next_button_kingdom = QtWidgets.QPushButton(self.Kingdoms)
        self.next_button_kingdom.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button_kingdom.sizePolicy().hasHeightForWidth())
        self.next_button_kingdom.setSizePolicy(sizePolicy)
        self.next_button_kingdom.setMinimumSize(QtCore.QSize(0, 0))
        self.next_button_kingdom.setObjectName("next_button_kingdom")
        self.horizontalLayout.addWidget(self.next_button_kingdom)
        BookViewContainer.addTab(self.Kingdoms, "")
        self.Warriors = QtWidgets.QWidget()
        self.Warriors.setObjectName("Warriors")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Warriors)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous_button = QtWidgets.QPushButton(self.Warriors)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_2.addWidget(self.previous_button)
        self.page_widget = QtWidgets.QWidget(self.Warriors)
        self.page_widget.setObjectName("page_widget")
        self.horizontalLayout_2.addWidget(self.page_widget)
        self.next_button = QtWidgets.QPushButton(self.Warriors)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 20)
        self.horizontalLayout_2.setStretch(2, 1)
        BookViewContainer.addTab(self.Warriors, "")
        self.Recit = QtWidgets.QWidget()
        self.Recit.setObjectName("Recit")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Recit)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 321, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.verticalLayoutWidget_3)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_3.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_3.addWidget(self.page_8)
        self.verticalLayout_3.addWidget(self.stackedWidget_3)
        BookViewContainer.addTab(self.Recit, "")

        self.retranslateUi(BookViewContainer)
        BookViewContainer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BookViewContainer)

    def retranslateUi(self, BookViewContainer):
        _translate = QtCore.QCoreApplication.translate
        self.kingdom_previous_button.setText(_translate("BookViewContainer", "Previous"))
        self.next_button_kingdom.setText(_translate("BookViewContainer", "Next"))
        BookViewContainer.setTabText(BookViewContainer.indexOf(self.Kingdoms), _translate("BookViewContainer", "Tab 1"))
        self.previous_button.setText(_translate("BookViewContainer", "Previous"))
        self.next_button.setText(_translate("BookViewContainer", "Next"))
        BookViewContainer.setTabText(BookViewContainer.indexOf(self.Warriors), _translate("BookViewContainer", "Tab 2"))
        BookViewContainer.setTabText(BookViewContainer.indexOf(self.Recit), _translate("BookViewContainer", "Page"))

