# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/View/book_warrior_page.ui'
#
# Created: Tue Dec  9 22:08:15 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookWarriorPage(object):
    def setupUi(self, BookWarriorPage):
        BookWarriorPage.setObjectName("BookWarriorPage")
        BookWarriorPage.resize(463, 380)
        BookWarriorPage.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookWarriorPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(BookWarriorPage)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.warrior_name = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warrior_name.sizePolicy().hasHeightForWidth())
        self.warrior_name.setSizePolicy(sizePolicy)
        self.warrior_name.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(24)
        self.warrior_name.setFont(font)
        self.warrior_name.setFrameShape(QtWidgets.QFrame.Panel)
        self.warrior_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warrior_name.setAlignment(QtCore.Qt.AlignCenter)
        self.warrior_name.setObjectName("warrior_name")
        self.verticalLayout.addWidget(self.warrior_name)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.profil_layout = QtWidgets.QHBoxLayout(self.widget_3)
        self.profil_layout.setContentsMargins(0, 0, 0, 0)
        self.profil_layout.setObjectName("profil_layout")
        self.picture_widget = QtWidgets.QWidget(self.widget_3)
        self.picture_widget.setObjectName("picture_widget")
        self.picture_layout = QtWidgets.QVBoxLayout(self.picture_widget)
        self.picture_layout.setContentsMargins(0, 0, 0, 0)
        self.picture_layout.setObjectName("picture_layout")
        self.profil_layout.addWidget(self.picture_widget)
        self.infos_widget = QtWidgets.QWidget(self.widget_3)
        self.infos_widget.setObjectName("infos_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infos_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rank_widget = QtWidgets.QWidget(self.infos_widget)
        self.rank_widget.setObjectName("rank_widget")
        self.layout_rank = QtWidgets.QHBoxLayout(self.rank_widget)
        self.layout_rank.setContentsMargins(0, 0, 0, 0)
        self.layout_rank.setObjectName("layout_rank")
        self.verticalLayout_3.addWidget(self.rank_widget)
        self.groupBox = QtWidgets.QGroupBox(self.infos_widget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_empire = QtWidgets.QLabel(self.groupBox)
        self.label_empire.setObjectName("label_empire")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_empire)
        self.label_royaume = QtWidgets.QLabel(self.groupBox)
        self.label_royaume.setObjectName("label_royaume")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_royaume)
        self.label_faction = QtWidgets.QLabel(self.groupBox)
        self.label_faction.setObjectName("label_faction")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_faction)
        self.label_avancement = QtWidgets.QLabel(self.groupBox)
        self.label_avancement.setObjectName("label_avancement")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_avancement)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.infos_widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 3)
        self.profil_layout.addWidget(self.infos_widget)
        self.profil_layout.setStretch(0, 3)
        self.profil_layout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(BookWarriorPage)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.warrior_description = QtWidgets.QPlainTextEdit(self.widget_2)
        self.warrior_description.setObjectName("warrior_description")
        self.verticalLayout_2.addWidget(self.warrior_description)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.warrior_techniques = QtWidgets.QPlainTextEdit(self.widget_2)
        self.warrior_techniques.setObjectName("warrior_techniques")
        self.verticalLayout_2.addWidget(self.warrior_techniques)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.listWidget = QtWidgets.QListWidget(self.widget_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 10)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(BookWarriorPage)
        QtCore.QMetaObject.connectSlotsByName(BookWarriorPage)

    def retranslateUi(self, BookWarriorPage):
        _translate = QtCore.QCoreApplication.translate
        BookWarriorPage.setWindowTitle(_translate("BookWarriorPage", "Form"))
        self.warrior_name.setText(_translate("BookWarriorPage", "TextLabel"))
        self.groupBox.setTitle(_translate("BookWarriorPage", "Infos"))
        self.label_2.setText(_translate("BookWarriorPage", "Empire"))
        self.label_7.setText(_translate("BookWarriorPage", "Royaume"))
        self.label_empire.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_royaume.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_faction.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label_avancement.setText(_translate("BookWarriorPage", "TextLabel"))
        self.label.setText(_translate("BookWarriorPage", "Faction"))
        self.label_8.setText(_translate("BookWarriorPage", "Avancement"))
        self.groupBox_2.setTitle(_translate("BookWarriorPage", "Attributs"))
        self.label_3.setText(_translate("BookWarriorPage", "Description"))
        self.label_4.setText(_translate("BookWarriorPage", "Techniques"))
        self.label_5.setText(_translate("BookWarriorPage", "Historique"))

import resources_rc
