# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_modules/View/profil_widget.ui'
#
# Created: Tue Dec  9 22:08:13 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_profilWidget(object):
    def setupUi(self, profilWidget):
        profilWidget.setObjectName("profilWidget")
        profilWidget.resize(228, 574)
        self.verticalLayoutWidget = QtWidgets.QWidget(profilWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 220, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.Title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Title.setFrameShape(QtWidgets.QFrame.Box)
        self.Title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title.setObjectName("Title")
        self.horizontalLayout.addWidget(self.Title)
        self.nextButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.picture = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.picture.setFrameShape(QtWidgets.QFrame.Panel)
        self.picture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.picture.setObjectName("picture")
        self.horizontalLayout_2.addWidget(self.picture)
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.faction_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.faction_name.setObjectName("faction_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.faction_name)
        self.empire_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.empire_name.setObjectName("empire_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.empire_name)
        self.royaume_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.royaume_name.setObjectName("royaume_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.royaume_name)
        self.groupe_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.groupe_name.setObjectName("groupe_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.groupe_name)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 171, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 140, 171, 71))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(profilWidget)
        QtCore.QMetaObject.connectSlotsByName(profilWidget)

    def retranslateUi(self, profilWidget):
        _translate = QtCore.QCoreApplication.translate
        profilWidget.setWindowTitle(_translate("profilWidget", "Form"))
        self.previousButton.setText(_translate("profilWidget", "PushButton"))
        self.Title.setText(_translate("profilWidget", "TextLabel"))
        self.nextButton.setText(_translate("profilWidget", "PushButton"))
        self.label_3.setText(_translate("profilWidget", "TextLabel"))
        self.label_2.setText(_translate("profilWidget", "TextLabel"))
        self.pushButton_3.setText(_translate("profilWidget", "PushButton"))
        self.picture.setText(_translate("profilWidget", "TextLabel"))
        self.groupBox.setTitle(_translate("profilWidget", "Informations generales"))
        self.label_5.setText(_translate("profilWidget", "Faction"))
        self.label_6.setText(_translate("profilWidget", "Empire"))
        self.label_7.setText(_translate("profilWidget", "Royaume"))
        self.label_8.setText(_translate("profilWidget", "Groupe"))
        self.faction_name.setText(_translate("profilWidget", "TextLabel"))
        self.empire_name.setText(_translate("profilWidget", "TextLabel"))
        self.royaume_name.setText(_translate("profilWidget", "TextLabel"))
        self.groupe_name.setText(_translate("profilWidget", "TextLabel"))
        self.groupBox_2.setTitle(_translate("profilWidget", "Informations detaillées"))
        self.label_9.setText(_translate("profilWidget", "Histoire"))
        self.label_10.setText(_translate("profilWidget", "Techniques"))

